services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: contenedor_app_clientesv6_redesign
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        networks:
            - red_clientes_v6

    nginx:
        image: nginx:alpine
        container_name: contenedor_nginx_clientesv6_redesign
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - red_clientes_v6

    mysql:
        image: mysql:8.0
        container_name: contenedor_mysql_clientesv6_redesign
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-db_clientes_v6}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?Define DB_PASSWORD in .env}
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - red_clientes_v6

volumes:
    mysql_data:
        driver: local

networks:
    red_clientes_v6:
        driver: bridge
